### ISSUE TITLE
Dilithium5 not enabled

### ISSUE THREAD

**Issue by christianpaquin** [open-quantum-safe/openssh-portable#131]
Any reason why Dilithium5 is not enabled in the [https://github.com/open-quantum-safe/openssh/blob/OQS-v8/oqs-template/generate.yml#L262](generate.yml) file? On purpose or oversight?

**Comment by dstebila** [comment]
I don't recall any particular reason... unless we had also not enabled Dilithium5 in OpenSSL due to the constraints on the number of active signature schemes at one point in time...?

**Comment by baentsch** [comment]
As far as I recall it was a random choice when doing #97: I enabled algs such as to get maximum test coverage while not adding too many algorithms (as I also think there's a limit in number of active sig algs): Thus, Dil5AES got enabled instead of Dil5. PR #132 changes this now in line with NIST decisions (also for Sphncs+).

**Comment by baentsch** [comment]
Fixed by #132
