### ISSUE TITLE
Sync with upstream OpenSSH v8.4-p1 release

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/openssh-portable#53]

**Comment by christianpaquin** [comment]
I updated the issue title to sync to [v8.2](https://www.openssh.com/txt/release-8.2) (vs. v8.1), released on 2020-02-14.

**Comment by christianpaquin** [comment]
This is a bit more complicated than I expected; although not that surprising given that going from v7 to v8 is a major release. I did an initial merge of the code ([here](https://github.com/christianpaquin/openssh-portable/tree/cp-v8_2)); there is some code that will need to be reviewed for potentially unknown side-effects, and I'm having trouble compiling the project because the build instructions changed (see the [build from git](https://github.com/christianpaquin/openssh-portable/tree/cp-v8_2) section of the README).

I'll put this on the ice for now, and get back to more immediate priorities. I'll get back to it later, or I'm happy to pass the baton to someone else.

@dstebila, I suggest pushing this after our spring release

**Comment by baentsch** [comment]
Can't this be closed with the availability of the OQS-v8 branch?
